name: Python Pipeline
on: push

jobs:
  RunPythonScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python hello.py
  RunPowerShellScript:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: '& $env:GITHUB_ACTION_PATH/hello.ps1'
        shell: powershell
  

